#!/usr/bin/env python3
print("Greek Letters")
print("---")
print("Α α Alpha")
print("Β β Beta")
print("Γ γ Gamma")
print("Δ δ Delta")
print("Ε ε Epsilon")
print("Ζ ζ Zeta")
print("Η η Eta")
print("Θ θ Theta")
print("Ι ι Iota")
print("Κ κ Kappa")
print("Λ λ Lambda")
print("Μ μ Mu")
print("Ν ν Nu")
print("Ξ ξ Xi")
print("Ο ο Omicron")
print("Π π Pi")
print("Ρ ρ Rho")
print("Σ σ ς")
print("Τ τ Tau")
print("Υ υ Upsilon")
print("Φ φ Phi")
print("Χ χ Chi")
print("Ψ ψ Psi")
print("Ω ω Omega")
